//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCD_Admin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class ProductImage
    {
        [DisplayName("ID")]
        public int id { get; set; }
        [DisplayName("Product")]
        public int productId { get; set; }
        [DisplayName("Image")]
        [DisplayName("ImagePath")]
        public string imagePath { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
