//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCD_Admin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            this.Customers = new HashSet<Customer>();
        }

        [DisplayName("Ticket")]
        public int ticketId { get; set; }
        [DisplayName("Room")]
        public int roomId { get; set; }
        [DisplayName("Seat")]
        public int seatId { get; set; }
        [DisplayName("Seat Name")]
        public string seatName { get; set; }
        [DisplayName("Movie")]
        public int movieId { get; set; }
        [DisplayName("Screening")]
        public int screeningId { get; set; }
        [DisplayName("Ticket Code")]
        public string TicketCode { get; set; }
    
        public virtual Movy Movy { get; set; }
        public virtual RoomSeat RoomSeat { get; set; }
        public virtual Screening Screening { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
